[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.build]
cmds = ["cd Chanaphonflix && dotnet publish -c Release -o /app/out"]

[start]
cmd = "dotnet /app/out/Chanaphonflix.dll"

[variables]
ASPNETCORE_URLS = "http://0.0.0.0:8080"
PORT = "8080"
